import os
import matplotlib. pyplot as plt
import pandas as pd
import seaborn as sns
os.makedirs("Level_1/Charts",exist_ok=True) 
df = pd.read_csv("Level_1/Cleaned_data.csv")
df.columns = df.columns.str.strip()
print("Columns in Csv:", df.columns.tolist())
print(df.head())
print(df.info())
print(df.describe())
print(df["Likes"]. value_counts())
print(df["Likes"].value_counts())
print(df.columns)
print(df["Sentiment"].value_counts())
print(df["Platform"]. value_counts())
print(df["Country"].value_counts())
print(df["Likes"].mean())
print(df["Retweets"].mean())
print(df[["Likes", "Retweets"]].corr())
sns.countplot(data=df, x="Sentiment")
plt.title("Distribution of Sentiments")
plt.close()
sns.countplot(data=df, x="Platform")
plt.title("Posts by Platform")
plt.xticks(rotation=45)
plt.close()
plt.hist(df["Likes"], bins=20)
plt.title("Distribution of likes")
plt.xlabel("Likes")
plt.ylabel("Frequency")
plt.close()
sns.scatterplot(data=df,x="Likes", y="Retweets")
plt.close()
sns.countplot(data=df, x="Sentiment")
plt.title("Distribution of Sentiments")
plt.savefig("Level_1/Charts/sentiment_distribution.png",dpi=300, bbox_inches="tight")
plt.close()
sns.countplot(data=df, x="Platform")
plt.title("Posts by Platform")
plt.xticks(rotation=45)
plt.savefig("Level_1/Charts/platform_distribution.png",dpi=300,bbox_inches="tight")
plt.close()
plt.hist(df["Likes"], bins=20)
plt.title("Distribution of Likes")
plt.xlabel("Likes")
plt.ylabel("Frequency")
plt.savefig("Level_1/Charts/likes_distributions.png",dpi=300,bbox_inches="tight")
plt.close()
sns.scatterplot(data=df,x="Likes",y="Retweets")
plt.title("Likes vs Retweets")
plt.savefig("Level_1/Charts/Likes_vs_retweets.png",dpi=300,bbox_inches="tight")
plt.close()
print("EDA completed sucessfully!")
